package ast.cexp;

import fr.sorbonne_u.cps.sensor_network.requests.interfaces.ExecutionStateI;

import java.io.Serializable;

import ast.rand.IRand;

/**
 * Represents a Less Than or Equal To comparison expression. This class
 * implements the Icexp interface for evaluating the expression.
 */
public class LeqCExp implements Icexp, Serializable {
	private static final long serialVersionUID = 12L;

	private IRand rand1;
	private IRand rand2;

	/**
	 * Constructs a Less Than or Equal To comparison expression with two random
	 * generators.
	 *
	 * @param rand1 The first random generator.
	 * @param rand2 The second random generator.
	 */
	public LeqCExp(IRand rand1, IRand rand2) {
		this.rand1 = rand1;
		this.rand2 = rand2;
	}

	/**
	 * Evaluates the Less Than or Equal To comparison expression.
	 *
	 * @param es The execution state.
	 * @return True if the value generated by rand1 is less than or equal to the
	 *         value generated by rand2, false otherwise.
	 */
	public boolean eval(ExecutionStateI es) {
		return rand1.eval(es) <= rand2.eval(es);
	}
}
